title: Software Testing Foundation
author: Nguyen Trang
email: trangndt@talent.ominext.com
description: > # this means to ignore newlines until "baseurl:"
hihihi

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
